WebPasswordManager/Models/LogOn.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;

namespace WebPasswordManager.Models
{
    public class LogOn
    {
        public string Password { get; set; }
        public bool ValidatePassword ()
        {
            if(String.IsNullOrWhiteSpace(this.Password))
            {
                return false;
            }

            var path = HttpContext.Current.Server.MapPath("~/App_Data/Security.txt");
            var f = File.ReadAllLines(path);

            var salt = f[0];
            var actualHash = f[1];

            var crypto = new SimpleCrypto.PBKDF2();
            var candidateHash = crypto.Compute(this.Password, salt);


            return crypto.Compare(actualHash, candidateHash);
        }
    }
}

WebPasswordManager/Models/PasswordAccount.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace WebPasswordManager.Models
{
    public class PasswordAccount
    {
        public int Id { get; set; }
        [Display(Name = "Account Name")]
        public string AccountName { get; set; }
        public string Url { get; set; }
        [Display(Name = "User Name")]
        public string UserName { get; set; }
        public string Password { get; set; }
        [Display(Name = "Account Owner")]
        public string AccountOwner { get; set; }
        [Display(Name = "Security Questions")]
        public string SecurityQuestions { get; set; }
    }
}

WebPasswordManager/Models/PasswordAccounts.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebPasswordManager.Models
{
    public class PasswordAccounts
    {
        public IEnumerable<PasswordAccount> Accounts { get; set; }
    }
}

WebPasswordManager/Models/SecurityQuestion.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebPasswordManager.Models
{
    public class SecurityQuestion
    {
        public string Question { get; set; }
        public string Answer { get; set; }
        public int AccountId { get; set; }
        public int Id { get; set; }
    }
}

WebPasswordManager/Controllers/LogOnController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPasswordManager.Models;

namespace WebPasswordManager.Controllers
{
    public class LogOnController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index ( Models.LogOn model )
        {
            if(!model.ValidatePassword())
            {
                ModelState.AddModelError(nameof(model.Password), "Invalid Password");
                return View();
            }

            MvcApplication.Password = model.Password;
            Repositories.SqlitePasswordManager.Init();
            return RedirectToAction("Index", "PasswordAccount");
        }
    }
}

WebPasswordManager/Controllers/PasswordAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPasswordManager.Models;
using WebPasswordManager.Repositories;
using Newtonsoft.Json;
using WebPasswordManager.Attributes;

namespace WebPasswordManager.Controllers
{
    [PasswordRequired]
    public class PasswordAccountController : Controller
    {
        IPManger passwordManager = new PManager();
        // GET: PasswordAccount
        public ActionResult Index()        {
            
            PasswordAccounts model = new PasswordAccounts();

            model.Accounts = passwordManager.GetAllAccounts();

            return View(model);
        }

        public ActionResult GetViewAccountById(int id)
        {
            var account = passwordManager.GetAccountByID(id);

            return View(account);
        }

        public ActionResult RemoveAccount(int id)
        {
            passwordManager.DeleteAccount(id);

            return RedirectToAction("Index", "PasswordAccount");
        }

        [HttpGet]
        public ActionResult AddAccount()
        {
            var model = new PasswordAccount();
            return View("AddPasswordAccount", model);
        }

        [HttpGet]
        public ActionResult EditAccount(int id)
        {
            var model = passwordManager.GetAccountByID(id);
            return View("EditPasswordAccount", model);
        }

        [HttpPost]
        public ActionResult SaveAccount(PasswordAccount model)
        {
            passwordManager.SaveAccount(model);
            return RedirectToAction("Index", "PasswordAccount");
        }
    }
}

WebPasswordManager/Views/LogOn/Index.cshtml
@model WebPasswordManager.Models.LogOn

@{

}

@using (Html.BeginForm("Index", "LogOn"))
{
    @Html.ValidationSummary()
    <div class="form-group">
        @Html.LabelFor(x => x.Password)
        @Html.PasswordFor(x => x.Password, new { @class = "form-control", placeholder = "Password" })
    </div>

    <button type="submit" class="btn btn-default">Submit</button>
}

WebPasswordManager/Views/PasswordAccount/AddPasswordAccount.cshtml
@model WebPasswordManager.Models.PasswordAccount
@{

}

<div>
    @using (Html.BeginForm("SaveAccount", "PasswordAccount"))
    {
        @Html.ValidationSummary() <br />
        <div class="form-group">
            @Html.LabelFor(x => x.AccountName)
            @Html.TextBoxFor(x => x.AccountName, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.Url)
            @Html.TextBoxFor(x => x.Url, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.UserName)
            @Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.Password)
            @Html.TextBoxFor(x => x.Password, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.AccountOwner)
            @Html.TextBoxFor(x => x.AccountOwner, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.SecurityQuestions)
            @Html.TextAreaFor(x => x.SecurityQuestions, new { @class = "form-control" })
        </div>

        @Html.ActionLink("Back", "Index", "PasswordAccount", null, new { @class = "btn btn-default" })
        <button type="submit" class="btn btn-primary">Submit</button>
    }
</div>

WebPasswordManager/Views/PasswordAccount/EditPasswordAccount.cshtml
@model WebPasswordManager.Models.PasswordAccount
@{
    
}

<div>
    @using (Html.BeginForm("SaveAccount", "PasswordAccount"))
    {
        @Html.ValidationSummary() <br />
        <div class="form-group">
            @Html.LabelFor(x => x.AccountName)
            @Html.TextBoxFor(x => x.AccountName, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.Url)
            @Html.TextBoxFor(x => x.Url, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.UserName)
            @Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.Password)
            @Html.TextBoxFor(x => x.Password, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.AccountOwner)
            @Html.TextBoxFor(x => x.AccountOwner, new { @class = "form-control" })
        </div>        
        <div class="form-group">
            @Html.LabelFor(x => x.SecurityQuestions)
            @Html.TextAreaFor(x => x.SecurityQuestions, new { @class = "form-control" })
        </div>
        
        @Html.HiddenFor(x => x.Id)
        @Html.ActionLink("Back", "Index", "PasswordAccount", null, new { @class = "btn btn-default" })
        <button type="submit" class="btn btn-primary">Submit</button>
    }
</div>

WebPasswordManager/Views/PasswordAccount/GetViewAccountById.cshtml
@model WebPasswordManager.Models.PasswordAccount
@{

}

<div>
    <dl>
        <dt>Account Name:  @Model.AccountName </dt>
        <dt>Url: @Model.Url</dt>
        <dt>User Name: @Model.UserName</dt>
        <dt>Password: @Model.Password</dt>
        <dt>Account Owner: @Model.AccountOwner</dt>
    </dl>
    @Html.ActionLink("Back", "Index", "PasswordAccount", null, new { @class = "btn btn-default" })
</div>

WebPasswordManager/Views/PasswordAccount/Index.cshtml
@model WebPasswordManager.Models.PasswordAccounts
@{

}

@Html.ActionLink("Add Account", "AddAccount", "PasswordAccount", null, new { @class = "btn btn-default" })<br /><br />
<div>
    <table class="table">
        <thead>
            <tr>
                <th>Account Name</th>
                <th>URL</th>
                <th>Delete</th>
            </tr>
        </thead>
    <tbody>
        @foreach (var account in Model.Accounts)
        {
            <tr>
                <td>@Html.ActionLink(account.AccountName, "EditAccount", "PasswordAccount", new { id = account.Id }, null)</td>
                <td><a href="@account.Url"></a>@account.Url</td>
                <td>@Html.ActionLink("Delete Account", "RemoveAccount", "PasswordAccount", new { id = account.Id }, new { @class = "btn btn-default" })</td>
            </tr>
        }
    </tbody>
</table>
    
</div>

WebPasswordManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@Page.Title</title>
    @RenderSection("head", required: false)
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/Cerulean/bootstrap.min.css" />

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
    
    <div class="container">
        <header>
            <h1>Password Manager</h1>
        </header>
        @RenderBody()
        <footer></footer>
    </div>
</body>
</html>